services:
  nats:
    image: nats:latest
    container_name: nats_jetstream
    command: ["-js", "--config", "/etc/nats/nats-auth.conf"]
    ports:
      - "4222:4222"
      - "8222:8222"
    volumes:
      - ./nats_data:/data
      - ./nats-auth.conf:/etc/nats/nats-auth.conf
    restart: no

  azuresqledge:
    image: mcr.microsoft.com/azure-sql-edge:latest
    container_name: azure_sql_edge
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: 'Y'
      SA_PASSWORD: 'P@assWord!'
    volumes:
      - ./mssql_data:/var/opt/mssql
    restart: no
    
  migrations:
    build:
      context: .
      dockerfile: ./TwitchChat.Application/Dockerfile.migrations
    depends_on:
      - azuresqledge
    environment:
      ConnectionStrings__Default: "Server=azure_sql_edge,1433;User Id=sa;Password=P@assWord!;Encrypt=False"
    restart: "no"
    
  twitchchat:
    build:
      context: .
      dockerfile: ./TwitchChat.Application/Dockerfile
    depends_on:
      migrations:
        condition: service_completed_successfully
      nats:
        condition: service_started
      azuresqledge:
        condition: service_started
    ports:
      - "5000:8080"
    restart: always

